export const REQUEST_NEWCOMPANY = 'REQUEST_NEWCOMPANY'
export const NEWCOMPANY_SUCCESS = 'NEWCOMPANY_SUCCESS'
export const NEWCOMPANY_FAILED = 'NEWCOMPANY_FAILED'

export const REDIRECT_TO_TC = 'REDIRECT_TO_TC'
