export const REQUEST_VERIFY = 'REQUEST_VERIFY'
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS'
export const VERIFY_FAILED = 'VERIFY_FAILED'

export const REQUEST_RESEND = 'REQUEST_RESEND'
export const RESEND_SUCCESS = 'RESEND_SUCCESS'
export const RESEND_FAILED = 'RESEND_FAILED'