export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const REQUEST_AUTHENTICATION = 'REQUEST_AUTHENTICATION'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'

export const TOGGLE_DARK = 'TOGGLE_DARK'

export const ASSUME_AMID = 'ASSUME_AMID'

// export const CHANGE_DATE_FORMAT = 'CHANGE_DATE_FORMAT'