// Dummy Data
export const fetchTransactions = () => Promise.resolve([
  {
    assetManagerId: 133,
    assetBookId: 'abc',
    counterpartyBookId: 'def',
    transactionAction: 'Buy',
    assetId: 'ghi',
    quantity: 1,
    transactionDate: '9999-12-31',
    settlementDate: '999-12-31',
    price: 2,
    transactionCurrency: 'USD',
    settlementCurrency: 'USD',
    asset: {},
    executionTime: '18:00:00',
    transactionType: 'Trade',
    transactionId: '0001',
    transactionStatus: 'Active',
    charges: {},
    codes: {},
    comments: {},
    links: {},
    parties: {},
    references: {},
    postings: {},
    createdBy: 'user',
    updatedBy: 'user',
    createdTime: '18:00:00',
    updatedTime: '18:00:00',
    version: 1
  },
  {
    assetManagerId: 133,
    assetBookId: 'abc',
    counterpartyBookId: 'def',
    transactionAction: 'Buy',
    assetId: 'ghi',
    quantity: 1,
    transactionDate: '9999-12-31',
    settlementDate: '999-12-31',
    price: 2,
    transactionCurrency: 'USD',
    settlementCurrency: 'USD',
    asset: {},
    executionTime: '18:00:00',
    transactionType: 'Trade',
    transactionId: '0002',
    transactionStatus: 'Active',
    charges: {},
    codes: {},
    comments: {},
    links: {},
    parties: {},
    references: {},
    postings: {},
    createdBy: 'user',
    updatedBy: 'user',
    createdTime: '18:00:00',
    updatedTime: '18:00:00',
    version: 1
  },
  {
    assetManagerId: 133,
    assetBookId: 'abc',
    counterpartyBookId: 'def',
    transactionAction: 'Buy',
    assetId: 'ghi',
    quantity: 1,
    transactionDate: '9999-12-31',
    settlementDate: '999-12-31',
    price: 2,
    transactionCurrency: 'USD',
    settlementCurrency: 'USD',
    asset: {},
    executionTime: '18:00:00',
    transactionType: 'Trade',
    transactionId: '0003',
    transactionStatus: 'Active',
    charges: {},
    codes: {},
    comments: {},
    links: {},
    parties: {},
    references: {},
    postings: {},
    createdBy: 'user',
    updatedBy: 'user',
    createdTime: '18:00:00',
    updatedTime: '18:00:00',
    version: 1
  }
])